### ISSUE TITLE
Missing Python Package gi

### ISSUE THREAD

**Issue by medoix** [stockmind/gpd-pocket-screen-indicator#1]
on base 17.04 install of ISO provided from "gpd-pocket-ubuntu-respin" the rotate screen script will not run because python-gi is not installed.

sudo apt install python-pi

resolves it.

**Comment by stockmind** [comment]
Thanks for suggestion, you can find dependencies in README:
https://github.com/stockmind/gpd-pocket-screen-indicator#debian-ubuntu-etc

Will look to make a package and a script check for dependencies

**Comment by medoix** [comment]
Ahh awesome thanks, i didn't see those there. This attempts to get auto installed from the update.sh script on the respin repo and that is fully automated so i incorrectly assumed something was broken. I might look to contribute  some tweaks. 👍

**Comment by stockmind** [comment]
You are right! I must update the dependencies install on update script, my bad!
